### ISSUE TITLE
Indices of state inputs

### ISSUE THREAD

**Issue by joacorapela** [nwfsc-timeseries/MARSS#110]
I have a system that at sample time n receives an input input[n]. I want to use this input to drive both the state and the observations. I am confused on how to build the c matrix of MARSS sate inputs.

In MARSS x_{n+1}=B x_n+u+C c_n+w_n. Therefore, I think the first column of c corresponds to n=0 and the last one
to n=N-1. Thus, in MARSS there cannot be an input to the last state and you have to provide an input to the initial state. Is this correct?

If yes, for my system should I append a first columns of zero as inputs to the initial state? And I think I cannot use an input to x_N, the last sample of the state.

Thanks for this great package.

Joaquin

**Comment by eeholmes** [comment]
Hi Joaquin,

The time-indexing for the MARSS equation in the MARSS package is

x(t) = B x(t-1) + u + C c(t) + w(t)

See for example documentation at ?MARSS. So not quite as you wrote it--Do let me know if it is not written this way in the documentation somewhere.  So the last state x(N) will be affected by c(N) and the first state x(1) will be affected by c(1).

y(t) = Z x(t) + a + D d(t)

So similarly, y(1) is affected by d(1) and y(N) is affected by d(N).

Sometimes one wants c(t) to affect x(t+1), in that case you do need to shift the indexing of the c() and put in a column of 0s at t=1 so that input at time t appears at t+1 in your model for MARSS.  That means putting in a column of 0s at t=1 and making columns 2:N be inputs at t=1 to N-1.

Does that make sense?

Regards,

Eli

**Comment by joacorapela** [comment]
Thanks for your reply Eli, as usual, very helpful. The equations of the MARSS model in MARSS.pdf from February 2020 (page 3) were as I stated. But now I see that these equations have changed as you describe in the newest version of this file from August 2020.

Cordially, Joaquin
