### ISSUE TITLE
Shared restrictions

### ISSUE THREAD

**Issue by pollytatouin** [nwfsc-timeseries/MARSS#63]
Hello MARSS team,

First of all, I want to thank you very much for all the work that you put into developing this package. It is very complete and it fills an area where R is a bit behind compared to other languages.

I saw in the documentation that it is not possible to specify parameter restrictions across matrices, but only within matrices. Is there a particular reason for this? I was thinking of diving into the code to see if I can't change this myself but thought it would be good to ask first if there is a particular problem with doing something like this.

Best,
Polly

**Comment by eeholmes** [comment]
Hi,

It is a mathematical reason having to the with the EM algorithm (see the write-up to the EM algorithm on the CRAN page). Doesn't have anything to do with the code. 

That said, you can easily incorporate the U into the B by writing your X equation with an X[1] (1st row) fixed at 1. Then the "u", appears in the [1,1] spot of your B matrix.  Similarly you can incorporate the A into the Z.

Also one can theoretically write a MARSS equation just with the X equation (so incorporate the Y into the X part). In this form, Q and R would be in a single Q equation and B and Z would be a single equation. The reason that the MARSS package doesn't do this is that traditionally one treats the X as 'hidden' (no data) and with this rewrite you need to have some of the X observed (the X that are really the Y). That derivation is going to take a re-derivation of the EM update equations (doable) but also the Kalman filter/smoother equations (ug). That's a lot of work.

Note it is not uncommon to write state-space models with Q and R correlated. This was because the package was originally inspired by MARSS models with independent Q & R.  But there are also identifiability issues for the models with correlated Q and R.

Note that if you write custom code to fit a MARSS model with something like optim() or a Bayesian model, you can definitely have sharing across matrices. Just be aware there are these funky ridges in the likelihood that are easy to create, which leads to a model that doesn't converge onto the maxima or that doesn't explore the likelihood space (for a Bayesian algorithm).

Regards,

Eli

**Comment by pollytatouin** [comment]
Hi Eli,

Thank you for those details. I see that there exist some work-arounds, although it can require quite a bit of work.

What I am really after and that you have not mentioned, is to impose shared restrictions between the D and Z matrices. Is this something that would be possible? Also, I am mostly interested in the BFGS algorithm for the moment, so perhaps this allows a bit more flexibility?

Best,
Polly

**Comment by eeholmes** [comment]
Yes you should be able to share D and Z. Just have to set up the Z properly.   No BFGS does not offer more flexibility in MARSS. You have the same matrix formulation of the models.

Here is an example:
```
TT=100
r=0.1
q=1
z=2
x=cumsum(rnorm(TT,0,sqrt(q)))
c=matrix(cos((1:TT)^0.5), nrow=1)
y=z*x + z*c + rnorm(TT,0,sqrt(r))
#y is our data with z shared in Z and D matrix

#Set up model with c in the y and have that tracked by a x that is =c (by setting R=0 for that x)
dat=rbind(c,y)

R=matrix(list(0),2,2)
diag(R)=list(0,"r")
Q=diag(c(1,q))
x0=matrix(list(c[1],"x0"),ncol=1)
A="zero"
Z=matrix(list(1,0,"z","z"),2,2, byrow=TRUE)

model.list=list(Z=Z,A=A,R=R,Q=Q,x0=x0,U="zero",tinitx=1)

fit=MARSS(dat, model=model.list, method="BFGS")
```

**Comment by eeholmes** [comment]
Also you can have linear constraints like
```
y=z*x + (a+2*z)*c + rnorm(TT,0,sqrt(r))
# would mean a Z like
Z=matrix(list(1,0, "a+2*z", "z"),2,2, byrow=TRUE)
#you can estimate both a and z
```

**Comment by eeholmes** [comment]
Note while writing the example above, I discovered that I introduced a bug into v 3.10.12 (on CRAN) that affects cases where R=0. It will only appear when you use residuals() but residuals() is used for diagnostic plots so those will look odd until I get the fix on CRAN. I pushed the fix to GitHub (master) but have not made a release yet.

**Comment by pollytatouin** [comment]
Hi Eli,

If I'm not mistaken, your configuration leaves the B matrix as the identity matrix. Thus it supposes that my exogenous covariate, c, follows a random walk. However, I don't want to assume any autoregressive structure for it, I just want to take the data as it is. 

I considered modifying the B matrix, but even then, since the state equations set up a lagged relationship with X, I don't know what to do. The model I'm trying to implement can be found in the Code Guide of the folder [here].(https://www.newyorkfed.org/medialibrary/media/research/economists/williams/data/HLW_Code.zip)

Thank you very much for your time and patience.

**Comment by eeholmes** [comment]
The R for c is 0, so the c covariate will just the data as it is. The B is set to identity and the Q largish (1) just so that the algorithm doesn't have to 'fight against itself' to make x[1,] = c .  'fight against itself' can happen if Q is small and B constraining because the step sizes in the EM algorithm get small. It would still find the same maximum LL but it might do so slower.

Note another approach is to make Z time-varying with elements  at time t like "a + a*c(t)", but a time-varying Z will be very slow. The approach I used which makes x[1,]=c will be faster.

**Comment by pollytatouin** [comment]
Ok thank you, I will try this out this week. 

Le 9 mars 2020 à 20:19, Eli Holmes <notifications@github.com> a écrit :

The R for c is 0, so the c covariate will just the data as it is. The B is set to identity and the Q largish (1) just so that the algorithm doesn't have to 'fight against itself' to make x[1,] = c .  'fight against itself' can happen if Q is small and B constraining because the step sizes in the EM algorithm get small. It would still find the same maximum LL but it might do so slower.

Note another approach is to make Z time-varying with elements at time t like "a + a*c(t)", but a time-varying Z will be very slow. The approach I used which makes x[1,]=c will be faster.
